name: 'Lerna Action'
description: 'Run lerna commands in actions without boilerplate'
inputs:
  root-cache:
    description: 'hash value to use in root package cache'
    required: true
    default: ${{ hashFiles('package-lock.json') }}
  packages-cache:
    description: 'hash value to use for lerna packages cache'
    required: true
    default: ${{ hashFiles('*/*/package-lock.json') }}
  thenPublish:
    description: '(Y/N) whether to publish packages after the action completes'
    required: false
    default: 'N'
runs:
  using: 'node12'
  main: 'dist/index.js'
