name: 'Lerna Action'
description: 'Run lerna commands in actions without boilerplate'
inputs:
  root-cache:
    description: 'hash value to use in root package cache'
    required: true
    default: ${{ hashFiles('package-lock.json') }}
  packages-cache:
    description: 'hash value to use for lerna packages cache'
    required: true
    default: ${{ hashFiles('**/package-lock.json')}}
runs:
  using: 'node12'
  main: 'dist/index.js'
